---
- hosts: all
  gather_facts: yes

  handlers:
    - import_tasks: handlers/handlers.yml

  tasks:
    - name: Ping host so we fail early if the host is not responding
      ping:

    - import_tasks: tasks/prereqs.yml
    - import_tasks: tasks/homebridge.yml
    - import_tasks: tasks/docker.yml
    - import_tasks: tasks/certbot.yml
    - import_tasks: tasks/zigbee2mqtt.yml
    - import_tasks: tasks/homeassistant.yml
    - import_tasks: tasks/pihole.yml
    - import_tasks: tasks/cups.yml
    - import_tasks: tasks/nginx.yml
