---

- name: create adguard opt dir
  file:
    dest: /opt/adguard/
    state: directory
    owner: root
    group: root
  become: true
  when: enable_adguard == 'yes'

- name: create adguard-conf dir
  file:
    dest: /opt/adguard/adguard-conf
    state: directory
    owner: root
    group: root
  become: true
  when: enable_adguard == 'yes'

- name: create adguard-work dir
  file:
    dest: /opt/adguard/adguard-work
    state: directory
    owner: root
    group: root
  become: true
  when: enable_adguard == 'yes'

- name: Copy adguard conf file
  copy:
    dest: /opt/adguard/adguard-conf/AdGuardHome.yaml
    owner: root
    group: root
    mode: '0644'
    content: |
      {{ adguard_custom_block }}
  become: true
  notify: restart adguard
  when: enable_adguard == 'yes'

- name: Copy adguard docker compose file
  template:
    src: adguard-docker-compose.yml.j2
    dest: /opt/adguard/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  become: true
  when: enable_adguard == 'yes'

- name: docker compose up adguard
  community.general.docker_compose:
    project_src: /opt/adguard/
    state: present
  when: enable_adguard == 'yes'

- ansible.builtin.set_fact:
    dns_lookup_adguard_via_adguard: "{{ lookup('community.general.dig', 'adguard.smbm.xyz', '@{{ ansible_default_ipv4.address }}' )}}"
    dns_adguard_ipv4: "{{ ansible_default_ipv4.address }}"

# - ansible.builtin.set_fact:
#     dns_adguard_up_bool: "{{ dns_adguard_ipv4 in dns_lookup_adguard_via_adguard }}"

- name: recreate resolv.conf quad9 plus adguard
  copy:
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    content: |
      nameserver 127.0.0.1
      nameserver 9.9.9.9
  become: true
  when: dns_adguard_ipv4 in dns_lookup_adguard_via_adguard

- name: recreate resolv.conf quad9 without adguard because we could not lookup adguard via adguard
  copy:
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    content: |
      nameserver 9.9.9.9
  become: true
  when: dns_adguard_ipv4 not in dns_lookup_adguard_via_adguard