---

- name: create adguard opt dir
  file:
    dest: /opt/adguard/
    state: directory
    owner: root
    group: root
  become: yes
  when: enable_adguard == 'yes'

- name: create adguard-conf dir
  file:
    dest: /opt/adguard/adguard-conf
    state: directory
    owner: root
    group: root
  become: yes
  when: enable_adguard == 'yes'

- name: create adguard-work dir
  file:
    dest: /opt/adguard/adguard-work
    state: directory
    owner: root
    group: root
  become: yes
  when: enable_adguard == 'yes'

# - name: Copy zigbee2mqtt config file
#   template:
#     src: zigbee2mqtt-configuration.yaml.j2
#     dest: /opt/zigbee2mqtt/zigbee2mqtt-data/configuration.yaml
#     owner: root
#     group: root
#     mode: '0644'
#     force: no
#   become: yes
#   when: enable_adguard == 'yes'

# - name: zigbee2mqtt config advanced custom block
#   ansible.builtin.blockinfile:
#     path: /opt/zigbee2mqtt/zigbee2mqtt-data/configuration.yaml
#     insertafter: EOF
#     block: "{{ zigbee2mqtt_custom_block }}"
#     state: present
#   become: yes
#   notify: restart zigbee2mqtt
#   when: enable_zigbee2mqtt == 'yes'

- name: Copy adguard docker compose file
  template:
    src: adguard-docker-compose.yml.j2
    dest: /opt/adguard/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: enable_adguard == 'yes'

- name: docker compose up adguard
  community.general.docker_compose:
    project_src: /opt/adguard/
    state: present
  when: enable_adguard == 'yes'