---

- name: Apt install cups
  apt:
    update_cache: yes
    name:
      - avahi-daemon
      - cups
      - printer-driver-brlaser
    state: present
  become: true
  when: enable_cups == 'yes'

- name: Add current user to lpadmin group
  user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: lpadmin
    append: yes
  become: true
  when: enable_cups == 'yes'

- name: Copy cupsd conf file
  template:
    src: cupsd-conf.j2
    dest: /etc/cups/cupsd.conf
    owner: root
    group: root
    mode: '0644'
  become: true
  notify: restart cups
  when: enable_cups == 'yes'