---

- name: Install Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: yes
  when: enable_pihole == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes'

- name: Add Docker repo
  apt_repository:
    repo: deb [arch=arm64] https://download.docker.com/linux/ubuntu focal stable
    filename: docker
    state: present
  become: yes
  when: enable_pihole == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes'

- name: Install Docker
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  become: yes
  when: enable_pihole == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes'

- name: Add current user to docker group
  user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: yes
  become: yes
  when: enable_pihole == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes'

- name: create docker daemon.json
  copy:
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "{{ ipv6_prefix_for_docker }}:40ed::/64"
      }
  become: yes
  notify:
    - restart docker
  when: enable_pihole == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes'

- name: Flushing handlers
  meta: flush_handlers

# Docker Compose

- name: Install pip docker-compose
  pip:
    name:
      docker-compose
  when: enable_pihole == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes'