---

- name: Get Docker GPG key
  get_url:
    url:  https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/trusted.gpg.d/docker.asc
  become: true
  when: install_docker == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes' or enable_adguard == 'yes'

- name: Add Docker repo
  apt_repository:
    repo: deb [signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
    filename: docker
    state: present
  become: true
  when: install_docker == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes' or enable_adguard == 'yes'

- name: Install Docker
  apt:
    update_cache: yes
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
  become: true
  when: install_docker == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes' or enable_adguard == 'yes'

- name: Add current user to docker group
  user:
    name: "{{ ansible_facts['user_id'] }}"
    groups: docker
    append: yes
  become: true
  when: install_docker == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes' or enable_adguard == 'yes'

- name: create docker daemon.json
  copy:
    dest: "/etc/docker/daemon.json"
    owner: root
    group: root
    content: |
      {
        "ipv6": true,
        "fixed-cidr-v6": "{{ ipv6_prefix_for_docker }}:40ee::/64"
      }
  become: true
  notify:
    - restart docker
  when: install_docker == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes' or enable_adguard == 'yes'

- name: Flushing handlers
  meta: flush_handlers

# Docker Compose

- name: Install pip docker-compose
  pip:
    name:
      docker-compose
  when: install_docker == 'yes' or enable_homeassistant == 'yes' or enable_zigbee2mqtt == 'yes' or enable_adguard == 'yes'