---

- name: Install Nodesource GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present
  become: yes
  when: enable_homebridge == 'yes'

- name: Add Nodesource repo
  apt_repository:
    repo: deb [arch=arm64] https://deb.nodesource.com/node_16.x focal main
    filename: nodesource
    state: present
  become: yes
  when: enable_homebridge == 'yes'

- name: Install Node 16.x
  apt:
    update_cache: yes
    name:
      - nodejs
  become: yes
  when: enable_homebridge == 'yes'

- name: Install "homebridge" node.js package.
  community.general.npm:
    name: homebridge
    global: yes
    unsafe_perm: yes
  become: yes
  when: enable_homebridge == 'yes'

- name: Install "homebridge-config-ui-x" node.js package.
  community.general.npm:
    name: homebridge-config-ui-x
    global: yes
    unsafe_perm: yes
  become: yes
  when: enable_homebridge == 'yes'

- name: Install Homebridge service and create admin user
  command: hb-service install --user homebridge
  become: yes
  args:
    creates: /var/lib/homebridge/config.json
  when: enable_homebridge == 'yes'