---

- name: unlink nginx default
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  become: yes
  notify:
    - reload nginx
  when: enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Copy pihole nginx conf file
  template:
    src: pihole-nginx-conf.j2
    dest: /etc/nginx/sites-available/pihole
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload nginx
  when: enable_pihole == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Symlink pihole nginx conf
  file:
    src: /etc/nginx/sites-available/pihole
    dest: /etc/nginx/sites-enabled/pihole
    owner: root
    group: root
    state: link
  become: yes
  notify: reload nginx
  when: enable_pihole == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Copy homebridge nginx conf file
  template:
    src: homebridge-nginx-conf.j2
    dest: /etc/nginx/sites-available/homebridge
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload nginx
  when: enable_homebridge == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'


- name: Symlink homebridge nginx conf
  file:
    src: /etc/nginx/sites-available/homebridge
    dest: /etc/nginx/sites-enabled/homebridge
    owner: root
    group: root
    state: link
  become: yes
  notify: reload nginx
  when: enable_homebridge == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Copy ruckus nginx conf file
  template:
    src: ruckus-nginx-conf.j2
    dest: /etc/nginx/sites-available/ruckus
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload nginx
  when: enable_ruckus == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Symlink ruckus nginx conf
  file:
    src: /etc/nginx/sites-available/ruckus
    dest: /etc/nginx/sites-enabled/ruckus
    owner: root
    group: root
    state: link
  become: yes
  notify: reload nginx
  when: enable_ruckus == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Copy cups nginx conf file
  template:
    src: cups-nginx-conf.j2
    dest: /etc/nginx/sites-available/cups
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload nginx
  when: enable_cups == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Symlink cups nginx conf
  file:
    src: /etc/nginx/sites-available/cups
    dest: /etc/nginx/sites-enabled/cups
    owner: root
    group: root
    state: link
  become: yes
  notify: reload nginx
  when: enable_cups == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Copy zigbee2mqtt nginx conf file
  template:
    src: zigbee2mqtt-nginx-conf.j2
    dest: /etc/nginx/sites-available/zigbee2mqtt
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload nginx
  when: enable_zigbee2mqtt == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Symlink zigbee2mqtt nginx conf
  file:
    src: /etc/nginx/sites-available/zigbee2mqtt
    dest: /etc/nginx/sites-enabled/zigbee2mqtt
    owner: root
    group: root
    state: link
  become: yes
  notify: reload nginx
  when: enable_zigbee2mqtt == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Copy homeassistant nginx conf file
  template:
    src: homeassistant-nginx-conf.j2
    dest: /etc/nginx/sites-available/homeassistant
    owner: root
    group: root
    mode: '0644'
  become: yes
  notify: reload nginx
  when: enable_homeassistant == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Symlink homeassistant nginx conf
  file:
    src: /etc/nginx/sites-available/homeassistant
    dest: /etc/nginx/sites-enabled/homeassistant
    owner: root
    group: root
    state: link
  become: yes
  notify: reload nginx
  when: enable_homeassistant == 'yes' and enable_nginx == 'yes' and enable_certbot == 'yes'

- name: Flushing handlers
  meta: flush_handlers