---

- name: create pihole opt dir
  file:
    dest: /opt/pihole/
    state: directory
    owner: root
    group: root
  become: yes
  when: enable_pihole == 'yes'

- name: Copy docker compose file
  template:
    src: pihole-docker-compose.yml.j2
    dest: /opt/pihole/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: enable_pihole == 'yes'

- name: docker compose up pihole
  community.general.docker_compose:
    project_src: /opt/pihole/
    state: present
  when: enable_pihole == 'yes'

- name: pihole custom domains
  ansible.builtin.blockinfile:
    path: /opt/pihole/etc-pihole/custom.list
    insertbefore: BOF
    create: yes
    block: |
      {{ global_ipv4 }} pihole.{{ domain }}
      {{ (enable_cups == 'yes') | ternary( global_ipv4 ~ ' cups.' ~ domain , None ) }}
      {{ (enable_homebridge == 'yes') | ternary( global_ipv4 ~ ' homebridge.' ~ domain , None) }}
      {{ (enable_zigbee2mqtt == 'yes') | ternary( global_ipv4 ~ ' z2m.' ~ domain , None) }}
      {{ (enable_homeassistant == 'yes') | ternary( global_ipv4 ~ ' ha.' ~ domain , None) }}
      {{ (enable_ruckus == 'yes') | ternary( global_ipv4 ~ ' ruckus.' ~ domain , None) }}
    state: present
  become: yes
  notify: restart pihole
  when: enable_pihole == 'yes'

- name: pihole allow iCloud private relay
  ansible.builtin.lineinfile:
    path: /opt/pihole/etc-pihole/pihole-FTL.conf
    insertafter: EOF
    line: BLOCK_ICLOUD_PR=false
    state: present
  become: yes
  notify: restart pihole
  when: enable_pihole == 'yes'

- name: Flushing handlers
  meta: flush_handlers