---

- name: Apt install deps
  apt:
    update_cache: yes
    name:
      - python3-pip
      - apt-transport-https
      - ca-certificates
      - gnupg-agent
      - curl
      - software-properties-common
      - gcc
      - g++
      - make
      - python3
      - net-tools
    state: present
  become: true

- name: Apt install bluetooth deps (will reboot afterwards if changes are made)
  apt:
    update_cache: yes
    name:
      - bluetooth
      - bluez
      - libbluetooth-dev
      - libudev-dev
    state: present
  become: true
  notify: reboot
  when: install_bluetooth == 'yes'

- name: Flushing handlers
  meta: flush_handlers

- name: Disable resolved
  systemd:
    name: systemd-resolved
    state: stopped
    enabled: no
  become: true
  notify:
    - unlink resolv dot conf

- name: Flushing handlers
  meta: flush_handlers

- name: Add hostname to hosts file
  lineinfile:
    path: /etc/hosts
    line: 127.0.0.1 {{ ansible_facts['hostname'] }}
  become: true