---

- name: create zigbee2mqtt opt dir
  file:
    dest: /opt/zigbee2mqtt/
    state: directory
    owner: root
    group: root
  become: yes
  when: enable_zigbee2mqtt == 'yes'

- name: create zigbee2mqtt-data dir
  file:
    dest: /opt/zigbee2mqtt/zigbee2mqtt-data
    state: directory
    owner: root
    group: root
  become: yes
  when: enable_zigbee2mqtt == 'yes'

- name: Copy zigbee2mqtt config file
  template:
    src: zigbee2mqtt-configuration.yaml.j2
    dest: /opt/zigbee2mqtt/zigbee2mqtt-data/configuration.yaml
    owner: root
    group: root
    mode: '0644'
    force: no
  become: yes
  when: enable_zigbee2mqtt == 'yes'

- name: zigbee2mqtt config advanced custom block
  ansible.builtin.blockinfile:
    path: /opt/zigbee2mqtt/zigbee2mqtt-data/configuration.yaml
    insertafter: EOF
    block: "{{ zigbee2mqtt_custom_block }}"
    state: present
  become: yes
  notify: restart zigbee2mqtt
  when: enable_zigbee2mqtt == 'yes'

- name: Copy zigbee2mqtt docker compose file
  template:
    src: zigbee2mqtt-docker-compose.yml.j2
    dest: /opt/zigbee2mqtt/docker-compose.yml
    owner: root
    group: root
    mode: '0644'
  become: yes
  when: enable_zigbee2mqtt == 'yes'

- name: docker compose up zigbee2mqtt
  community.general.docker_compose:
    project_src: /opt/zigbee2mqtt/
    state: present
  when: enable_zigbee2mqtt == 'yes'