---

- name: reboot
  ansible.builtin.reboot:
    msg: "Rebooting triggered by Ansible"
  become: true

- name: unlink resolv dot conf
  file:
    path: "/etc/resolv.conf"
    state: absent
  become: true
  notify:
    - recreate resolv.conf quad9

- name: recreate resolv.conf quad9
  copy:
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    content: |
      nameserver 9.9.9.9
  become: true

- name: restart docker
  systemd:
    name: docker.service
    state: restarted
  become: true

- name: restart cups
  systemd:
    name: cups.service
    state: restarted
  become: true

- name: set cerbot plugin containment
  command: snap set certbot trust-plugin-with-root=ok
  become: true

- name: reload nginx
  systemd:
    name: nginx.service
    state: reloaded
  become: true

- name: restart pihole
  community.general.docker_compose:
    project_src: /opt/pihole/
    state: present
    restarted: 'yes'
    services:
      - pihole

- name: restart homeassistant
  community.general.docker_compose:
    project_src: /opt/homeassistant/
    state: present
    restarted: 'yes'
    services:
      - homeassistant

- name: restart zigbee2mqtt
  community.general.docker_compose:
    project_src: /opt/zigbee2mqtt/
    state: present
    restarted: 'yes'
    services:
      - zigbee2mqtt

- name: restart adguard
  community.general.docker_compose:
    project_src: /opt/adguard/
    state: present
    restarted: 'yes'
    services:
      - adguard

- name: Tailscale Status
  listen: Confirm Tailscale is Connected
  ansible.builtin.command: tailscale status
  register: handlers_tailscale_status

- name: Assert Tailscale is Connected
  listen: Confirm Tailscale is Connected
  ansible.builtin.assert:
    that:
      - handlers_tailscale_status.stdout | length != 0
      - handlers_tailscale_status.stdout is not match('\[L\+V9o\]')